name: Update pre-fetched descriptions from pfadinamen.ch

on:
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  update:
    name: "Update pre-fetched descriptions from pfadinamen.ch"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - run: yarn install

      - run: yarn run fetch-descriptions

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update descriptions from pfadinamen.ch
          file_pattern: names.json
